version: '3.7'

services:
  mssql:
    build:
      context: ./DB
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pass1234567890"
    ports:
      - "1433:1433"
    networks:
      - appnet

  server:
    build: ./server
    depends_on:
      - mssql
    ports:
      - "8080:8080"
    networks:
      - appnet

  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet: