version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet

  server:
    build: ./server
    depends_on:
      - mssql
    environment:
      - SQL_USER=sa
      - SQL_PASSWORD=pass123
      - SQL_SERVER=msqsl
      - SQL_DATABASE=Questionnaires
    ports:
      - "8080:8080"
    networks:
      - appnet

  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet: