version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./DB/configure-db.sh:/choto/configure-db.sh
      - ./DB/setup.sql:/choto/setup.sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pass1234567890"
    ports:
      - "1433:1433"
    networks:
      - appnet

  server:
    build: ./server
    depends_on:
      - mssql
    ports:
      - "8080:8080"
    networks:
      - appnet

  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet: